refactored to simplify use of plans

diff --git a/launch b/launch
--- a/launch
+++ b/launch
@@ -8,9 +8,15 @@ fi
 
 DROPLET_NAME=$1
 DROPLET_SIZEID=66
-DROPLET_IMAGEID=562354 # centos 6.4 x64 (use tugboat images -g to see them)
 DROPLET_REGIONID=1
 SHIP_TYPE=$2
+
+if [ ! -d "./plans/$SHIP_TYPE" ]; then
+  echo "Cannot find plans for $SHIP_TYPE"
+  exit 1
+fi
+
+source "./plans/$SHIP_TYPE/plan.cfg"
 
 tugboat info $DROPLET_NAME
 
@@ -36,24 +42,14 @@ if [ $DROPLET_EXISTS -ne 0 ]
 	ssh-keygen -R $IP 
 fi
 
-# update
-echo 'updating droplet'
-ssh root@$IP "/usr/bin/yum -y update"
-
-# install puppet
-echo 'installing puppet'
-set +e
-#ssh root@$IP "/bin/rpm -Uvh http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm"
-ssh root@$IP "/bin/rpm -Uvh http://yum.puppetlabs.com/el/6/products/i386/puppetlabs-release-6-7.noarch.rpm"
-set -e
-ssh root@$IP "/usr/bin/yum -y install puppet"
-
-# apply puppet plans
+# copy plans
 ssh root@$IP "/bin/mkdir -p /plans"
 pushd "./plans/$SHIP_TYPE"
 scp -r "." root@$IP:/plans
 popd
-ssh root@$IP "puppet apply /plans/default.pp"
+
+# bootstrap
+ssh root@$IP $BOOTSTRAP_COMMAND
 
 # finished
 tugboat info $DROPLET_NAME
